[package]
name = "protologic_fleets"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Jerald/protologic_fleets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
